#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

test "$(basename "$root")" = "prueba_camara"
grep -Eq '^ofxOpenCv$' "$root/addons.make"
test -f "$root/bin/data/haarcascade_frontalface_default.xml"
test -f "$root/prueba_camara.code-workspace"
! test -f "$root/template_of.code-workspace"
grep -Eq '#include "ofxCvHaarFinder\.h"' "$root/src/ofApp.h"
grep -Eq 'ofxCvHaarFinder[[:space:]]+path144FaceFinder' "$root/src/ofApp.h"
grep -Eq 'ofRectangle[[:space:]]+path144Bounds' "$root/src/ofApp.h"
grep -Eq 'glm::vec2[[:space:]]+path144CameraFocus' "$root/src/ofApp.h"
grep -Eq 'bool[[:space:]]+path144TrackingEnabled[[:space:]]*=[[:space:]]*true' "$root/src/ofApp.h"
grep -Eq 'actualizarTrackingRostroPath144\(\)' "$root/src/ofApp.h" "$root/src/ofApp.cpp"
grep -Eq 'path144FaceFinder\.findHaarObjects' "$root/src/ofApp.cpp"
grep -Eq 'if \(!path144TrackingEnabled\)' "$root/src/ofApp.cpp"
grep -Eq "case 't':[[:space:]]*path144TrackingEnabled[[:space:]]*=[[:space:]]*!path144TrackingEnabled" "$root/src/ofApp.cpp"
grep -Eq 'tracking[[:space:]]*=[[:space:]]*path144TrackingEnabled[[:space:]]*\?' "$root/src/ofApp.cpp"
grep -Eq 'uniform vec4 pathBounds' "$root/src/ofApp.cpp"
grep -Eq 'uniform vec2 focusCenter' "$root/src/ofApp.cpp"
grep -Eq 'uniform float mirrorCamera' "$root/src/ofApp.cpp"
grep -Eq 'targetUv[[:space:]]*=[[:space:]]*clamp\(\(canvasPosition - pathBounds\.xy\) / pathBounds\.zw' "$root/src/ofApp.cpp"
grep -Eq 'effectiveFocus\.x[[:space:]]*=[[:space:]]*1\.0 - effectiveFocus\.x' "$root/src/ofApp.cpp"
grep -Eq 'cameraUv\.x[[:space:]]*=[[:space:]]*1\.0 - cameraUv\.x' "$root/src/ofApp.cpp"
grep -Eq 'setUniform4f\("pathBounds"' "$root/src/ofApp.cpp"
grep -Eq 'setUniform2f\("focusCenter"' "$root/src/ofApp.cpp"
grep -Eq 'setUniform1f\("mirrorCamera",[[:space:]]*1\.0f\)' "$root/src/ofApp.cpp"
